pipeline {
  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '3'))
    disableConcurrentBuilds()
    timestamps()
    timeout(time: 10, unit: 'MINUTES')
  }
  agent { label 'ec2-fleet' }
 stages {
    stage('Terraform') {
      steps {
          withCredentials([usernamePassword(credentialsId: 'aws_hub_ecr_repo', passwordVariable: 'pass', usernameVariable: 'user')]) {
              sh """
                 export AWS_DEFAULT_REGION=eu-west-1
                 export AWS_SECRET_ACCESS_KEY=iBH7HgySB9pBWX6Yu4Pht16vdjRsGdpJocV2ryy0
                 export AWS_ACCESS_KEY_ID=AKIAQI7GRHZBX72Y72ME
                 cat ~/.aws/config
                 cd api_gw_lambda
                 wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
                 unzip terraform_1.5.6_linux_amd64.zip
                 sudo mv terraform /usr/local/bin
                 terraform init
                 terraform apply --auto-approve
              """
              script
              {
                 royal_cognito_user_pool_arn = sh(returnStdout: true, script: "cd api_gw_lambda;  terraform output royal_cognito_user_pool_arn").trim()
                 royal_cognito_user_pool_endpoint = sh(returnStdout: true, script: "cd api_gw_lambda; terraform output royal_cognito_user_pool_endpoint").trim()
                 royal_cognito_user_pool_name = sh(returnStdout: true, script: "cd api_gw_lambda; terraform output royal_cognito_user_pool_name").trim()
                 royal_user_pool_client_id = sh(returnStdout: true, script: "cd api_gw_lambda;  terraform output royal_user_pool_client_id").trim()
                 royal_user_pool_id = sh(returnStdout: true, script: "cd api_gw_lambda; terraform output royal_user_pool_id").trim()
              }
              sh """
                 echo "royal_cognito_user_pool_arn: ${royal_cognito_user_pool_arn}"
                 echo "royal_cognito_user_pool_endpoint: ${royal_cognito_user_pool_endpoint}"
                 echo "royal_cognito_user_pool_name: ${royal_cognito_user_pool_name}"
                 echo "royal_user_pool_client_id: ${royal_user_pool_client_id}"
                 echo "royal_user_pool_id: ${royal_user_pool_id}"
                 aws cognito-idp sign-up --client-id ${royal_user_pool_client_id}  --username 'bibiefrat' --password 'a3bAcd01~' --user-attributes Name=name,Value='bibi' Name=email,Value='bibi.efrat@gmail.com'
                 aws cognito-idp admin-confirm-sign-up  --user-pool-id ${royal_user_pool_id} --username 'bibiefrat'
                 aws cognito-idp initiate-auth --client-id ${royal_user_pool_client_id}  --auth-flow USER_PASSWORD_AUTH --auth-parameters USERNAME='bibiefrat',PASSWORD='a3bAcd01~' --query 'AuthenticationResult.IdToken' --output text
                 sleep 60
              """




          }//withCredentials
      }//steps
    }//stage
  }//stages
post {
        always {
                  sh """
                    cd api_gw_lambda
                    terraform destroy -auto-approve

                  """
        }
  }
}